export type FundInfoListItemType = {
  code: string,
  name: string,
  nameCode: string,
  companyNetWorth: string,
  currentDate: string,
  cumulativeNetWorth: string,
  dayGrowthRate: string,
  weekGrowthRate: string,
  seasonGrowthRate: string,
  halfYearGrowthRate: string,
  yearGrowthRate: string,
  year3GrowthRate: string,
  thisYearGrowthRate: string,
  yearGrowthRateAll: string,
  creationTime: string,
  monthGrowthRate: string,
  year2GrowthRate: string,
}
